name: Github actions for Front End PR's and Pushes

on:
  push:
    branches: react-blinkist
    

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependency
        run: npm install
      - name: Build npm project
        run: npm run build --if-present
      # - name: Run test cases
      #   run: npm test
      # env:
      #   CI: true
     
      - name: Run tests
        run: npm run test --coverage
        # working-directory: './frontend-project'
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
